name: flutter_zoned
description: Zone scopes for flutter widgets.
version: 0.1.3
homepage: https://github.com/AndreasOlofsson/flutter_zoned

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
